AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  a stack with one lambda that gets called from another account.

Resources:
  CalledFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      InlineCode: |
        exports.handler = function(event, context) {
          console.log(event.message);
          context.succeed({message: "called with: " + event.message});
        }
  InvokeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: # this part says who can do it (principle)
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "AWS": "arn:aws:iam::663985455444:root" # Improve this - https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html
              },
              "Action": "sts:AssumeRole",
              "Condition": { } # Here you can limit things by say, the runtime that is trying to assume the role (although I think that's the user agent which should be used with caution)
                               # - https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html
            }
          ]
        }
      Policies:
        - PolicyName: AllowOtherAccountToInvokeAnyLambda
          PolicyDocument:
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Sid": "InvokeLambdaFunction",
                  "Effect": "Allow",
                  "Action": [
                      "lambda:InvokeFunction"
                  ],
                  "Resource": "*"
                }
              ]
            }
          # There could be other policies allowing access to a DynamoDb for example (or that could be a separate role).
      Description: The other account can assume this role and invoke any Lambda. Changign Resource can narrow the scope.

Outputs:
  FunctionToCall:
    Description: The name of the function that will be called
    Value: !Ref CalledFunction
    Export:
      Name: FunctionToCall

  FunctionToCallArn:
    Description: The ARN of the function that will be called
    Value: !GetAtt CalledFunction.Arn
    Export:
      Name: FunctionToCallArn

  InvokeLamdbaRoleArn:
    Description: The ARN of the InvokeLamdbaRole
    Value: !GetAtt InvokeLambdaRole.Arn
    Export:
      Name: InvokeLambdaRoleArn
