name: Check PR

on: pull_request

jobs:
  build:
    name: Build
    uses: alphagov/di-onboarding-product-page/.github/workflows/build.yml@0fc71869649811ea52287bc833949a78730c653e

  run-unit-tests:
    name: Run tests
    uses: alphagov/di-onboarding-product-page/.github/workflows/run-unit-tests.yml@0fc71869649811ea52287bc833949a78730c653e

  deploy-preview:
    name: Preview
    needs: build
    uses: alphagov/di-onboarding-product-page/.github/workflows/deploy-to-paas.yml@e5a1f487a479318759f644da1c3b78fba2bf5efc
    with:
      environment: preview
      cf_space_name: product-pages-preview
      app_name: di-pp-prev-${{ github.head_ref }}
    secrets:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
      register_spreadsheet_id: ${{ secrets.REGISTER_SPREADSHEET_ID }}
      request_spreadsheet_id: ${{ secrets.REQUEST_SPREADSHEET_ID }}

  run-acceptance-tests:
    name: Run tests
    needs: deploy-preview
    uses: alphagov/di-onboarding-product-page/.github/workflows/run-acceptance-tests.yml@afc46a2e0f0bf612dbfd3171af1c4ce322e608e4
    with:
      host: ${{ needs.deploy-preview.outputs.deployment_url }}
