name: Check PR

on: pull_request

jobs:
  build:
    name: Build
    uses: alphagov/di-onboarding-product-page/.github/workflows/build.yml@0fc71869649811ea52287bc833949a78730c653e

  run-unit-tests:
    name: Run tests
    uses: alphagov/di-onboarding-product-page/.github/workflows/run-unit-tests.yml@0fc71869649811ea52287bc833949a78730c653e

  deploy-preview:
    name: Preview
    needs: build
    uses: alphagov/di-onboarding-product-page/.github/workflows/deploy-to-paas.yml@0fc71869649811ea52287bc833949a78730c653e
    with:
      environment: preview
      cf_space_name: product-pages-preview
      app_name: di-pp-prev-${{ github.head_ref }}
      url: https://di-pp-prev-${{ github.head_ref }}.london.cloudapps.digital
      use_stub_zendesk: true
    secrets:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
      register_spreadsheet_id: ${{ secrets.REGISTER_SPREADSHEET_ID }}
      request_spreadsheet_id: ${{ secrets.REQUEST_SPREADSHEET_ID }}

  run-acceptance-tests:
    name: Run tests
    needs: deploy-preview
    uses: alphagov/di-onboarding-product-page/.github/workflows/run-acceptance-tests.yml@0fc71869649811ea52287bc833949a78730c653e
