name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    uses: alphagov/di-onboarding-product-page/.github/workflows/build.yml@95719f04dff575c2b468f69e49e50ef118228797

  run-unit-tests:
    name: Run tests
    uses: alphagov/di-onboarding-product-page/.github/workflows/run-unit-tests.yml@95719f04dff575c2b468f69e49e50ef118228797

  deploy-test:
    name: Test
    needs: [build, run-unit-tests]
    uses: alphagov/di-onboarding-product-page/.github/workflows/deploy-to-paas.yml@95719f04dff575c2b468f69e49e50ef118228797
    with:
      environment: test
      cf_space_name: product-pages-test
      url: https://di-product-page-test.london.cloudapps.digital
      use_stub_zendesk: true
    secrets:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
      register_spreadsheet_id: ${{ secrets.REGISTER_SPREADSHEET_ID }}
      request_spreadsheet_id: ${{ secrets.REQUEST_SPREADSHEET_ID }}

  run-acceptance-tests:
    name: Run tests
    needs: deploy-test
    uses: alphagov/di-onboarding-product-page/.github/workflows/run-acceptance-tests.yml@95719f04dff575c2b468f69e49e50ef118228797

  deploy-production:
    name: Publish
    needs: run-acceptance-tests
    uses: alphagov/di-onboarding-product-page/.github/workflows/deploy-to-paas.yml@95719f04dff575c2b468f69e49e50ef118228797
    with:
      environment: production
      cf_space_name: product-pages-production
      url: https://di-product-page.london.cloudapps.digital
      use_stub_zendesk: true
    secrets:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
      register_spreadsheet_id: ${{ secrets.REGISTER_SPREADSHEET_ID }}
      request_spreadsheet_id: ${{ secrets.REQUEST_SPREADSHEET_ID }}
