name: Deploy branch

on: workflow_dispatch

jobs:
  build:
    name: Build
    uses: alphagov/di-onboarding-product-page/.github/workflows/build.yml@0fc71869649811ea52287bc833949a78730c653e

  deploy-preview:
    name: Preview
    needs: build
    uses: alphagov/di-onboarding-product-page/.github/workflows/deploy-to-paas.yml@f4bcebd6ce722d586f634bfb64c15d4e54db0eec
    with:
      environment: preview
      cf_space_name: product-pages-preview
      app_name: di-pp-prev-${{ github.ref_name }}
    secrets:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
      register_spreadsheet_id: ${{ secrets.REGISTER_SPREADSHEET_ID }}
      request_spreadsheet_id: ${{ secrets.REQUEST_SPREADSHEET_ID }}
