name: Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    uses: alphagov/di-onboarding-product-page/.github/workflows/build.yml@0fc71869649811ea52287bc833949a78730c653e

  run-unit-tests:
    name: Run tests
    uses: alphagov/di-onboarding-product-page/.github/workflows/run-unit-tests.yml@0fc71869649811ea52287bc833949a78730c653e

  deploy-test:
    name: Test
    needs: [build, run-unit-tests]
    uses: alphagov/di-onboarding-product-page/.github/workflows/deploy-to-paas.yml@f4bcebd6ce722d586f634bfb64c15d4e54db0eec
    with:
      environment: test
      cf_space_name: product-pages-test
      url: https://di-product-page-test.london.cloudapps.digital
    secrets:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
      register_spreadsheet_id: ${{ secrets.REGISTER_SPREADSHEET_ID }}
      request_spreadsheet_id: ${{ secrets.REQUEST_SPREADSHEET_ID }}

  run-acceptance-tests:
    name: Run tests
    needs: deploy-test
    uses: alphagov/di-onboarding-product-page/.github/workflows/run-acceptance-tests.yml@afc46a2e0f0bf612dbfd3171af1c4ce322e608e4
    with:
      host: ${{ needs.deploy-test.outputs.deployment_url }}

  deploy-production:
    name: Publish
    needs: run-acceptance-tests
    uses: alphagov/di-onboarding-product-page/.github/workflows/deploy-to-paas.yml@f4bcebd6ce722d586f634bfb64c15d4e54db0eec
    with:
      environment: production
      cf_space_name: product-pages-production
      url: https://www.sign-in.service.gov.uk
      use_stub_zendesk: false
      rolling_deployment: true
      instances: 3
      google_tag_id: GTM-W38DXV2
    secrets:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
      zendesk_group_id: ${{ secrets.ZENDESK_GROUP_ID }}
      zendesk_username: ${{ secrets.ZENDESK_USERNAME }}
      zendesk_api_token: ${{ secrets.ZENDESK_API_TOKEN }}
      register_spreadsheet_id: ${{ secrets.REGISTER_SPREADSHEET_ID }}
      request_spreadsheet_id: ${{ secrets.REQUEST_SPREADSHEET_ID }}
