name: Acceptance tests

on:
  workflow_call:
    inputs:
      host: { required: false, type: string }

jobs:
  run-acceptance-tests:
    name: Acceptance
    runs-on: ubuntu-latest
    env:
      HOST: ${{ inputs.host }}
    steps:
      - name: Pull repository
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
      - name: Install Node dependencies
        run: npm install

      - name: Run cucumber acceptance tests
        run: npm run cucumbers
