name: Test PR

on: pull_request

jobs:
  build:
    name: Build
    uses: alphagov/di-onboarding-product-page/.github/workflows/build.yml@f750c28d35c2dce51c78ad36b6e112e8cf0ec62b

  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
      - name: Install Node dependencies
        run: npm install

      - name: Run mocha tests
        run: npm run test

  deploy-preview:
    name: Preview
    needs: build
    uses: alphagov/di-onboarding-product-page/.github/workflows/deploy.yml@f750c28d35c2dce51c78ad36b6e112e8cf0ec62b
    with:
      environment: preview
      app_name: di-product-page-preview-${{ github.head_ref }}
      url: https://di-product-page-preview-${{ github.head_ref }}.london.cloudapps.digital
      use_stub_zendesk: true
    secrets:
      CF_USERNAME: ${{ secrets.CF_USERNAME }}
      CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      ZENDESK_API_TOKEN: ${{ secrets.ZENDESK_API_TOKEN }}
      REGISTER_SPREADSHEET_ID: ${{ secrets.REGISTER_SPREADSHEET_ID }}
      REQUEST_SPREADSHEET_ID: ${{ secrets.REQUEST_SPREADSHEET_ID }}

  run-acceptance-tests:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    needs: deploy-preview
    steps:
      - run: echo "Ask John"
